## HW Set #1
Group Members' Names and Student IDs

1. Jasper Yang (19469535)

2. Xuanfu Zhu (77225654)

3. Yashas Ganesh Prasad (44773950)

4. Taha Memon (40222937)

5. Syed Zaim Naqvi (65443590)

### Instructions

Show your codes clearly and run them to produce desired results. Add commnets where appropriate. If necessary or as asked, add markdown cell(s) to explain your codes or answer the questions. Specifically:

- Create or add new code cell(s) next to each question and provide your codes in that cell.
- Run your codes and display the answers.
- As necessary use print() command to display your results.
- You may create one or multiple code cells for each question.
- You may add explanation followed by # sign next to codes as nexessary.

### Part A: Basic Python (30 points)

**Question #1 (8 pts)**
- Create a list of numbers from 1 to 10.
- Print the list
- Print the first and last elements of the list
- Print the length of the list

In [240]:

lst = list(range(1,11)) #create list from 1 to 10
print(lst) #print the list
print(lst[0]) #Print First element
print(lst[9]) #Print Last element
print(len(lst)) #Print length of list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
10
10


**Question #2 (12 pts)** Yashas

Given the string: s = "Quantitative" 
- convert it to uppercase
- print the number of characters in s
- Append the string " Economics" to s and print the result
- Reverse the string s
- Print the first 5 characters of s
- Count how many times the letter "t" appears in s

In [320]:
s = "Quantitative" #create string
print(s)

Quantitative


In [243]:
#part 1: convert it to uppercase
print(s.upper())

QUANTITATIVE


In [244]:
#part 2: print the number of characters in s
print(len(s))

12


In [245]:
#part 3: Append the string " Economics" to s and print the result
snew = s + " Economics"
print(snew)
#cannot use the append method, as original s is a string and not a list

Quantitative Economics


In [246]:
#part 4: Reverse the string s
print(s[::-1])
# if the basic slicing syntax[start : end : step], omitting the start and end, tells Python to start the slicing
# to start from the beginning and stop at the end, the negative 1 tells Python to move backwards/reverse
#Note Strings are immutable are s.reverse() so s.reverse() does not work here as it's only for lists

evitatitnauQ


In [247]:
#part 5
print(s[0:5])
# helps slice s from index 0 to index 4 (0,1,2,3,4), knowing that it will not bring out index 5

Quant


In [248]:
#part 6
print(s.count("t"))
#helps return the number of times "t" is in "quantitative"

3


***Question #3 (10 pts)*** Zaim

- Create a dictionary named *person* with keys "name", "age", and "country".
- Print the value of country using its key.
- add a new key occupation with appropriate value.
- update the value of age by adding 2 to it. If the age is 18, make it 20.
- use f string to convert the dictionary you created into a sentence. Example: print(f"My name is {name} ... ")

In [250]:
person = {"Name": "Felix", "Age": 21, "Country": "Canada"}
print(person)
print(person["Country"])
#creates and prints dictionary for person named felix with indicated age and country.
#Prints value of country for this person

{'Name': 'Felix', 'Age': 21, 'Country': 'Canada'}
Canada


In [251]:
person["Sex"] = "Male"
print(person)
#Adds a new key for Felix which is sex (male) and prints it.

{'Name': 'Felix', 'Age': 21, 'Country': 'Canada', 'Sex': 'Male'}


In [252]:
person["Age"] = person["Age"]+2
print(person)
#Adds 2 to Felix's age and prints it.

{'Name': 'Felix', 'Age': 23, 'Country': 'Canada', 'Sex': 'Male'}


In [253]:
print(f"My name is {person['Name']}, I am age {person['Age']} as well as a {person['Sex']} and live in {person['Country']}")
# Use f"string to convert info on Felix in sentence with print

My name is Felix, I am age 23 as well as a Male and live in Canada


### Part B: Control Flow (20 points)

***Question #4 (4 pts)***
- Choose any number and then use if and elif statements to check whether this number is positive, negative, or zero.

In [255]:
# Check whether 35 is positive or negative, or zero and print it
x = 35
if x < 0:
    print("the number ", x ,"is negative.")
elif x ==0:
    print("the number:", x ,"is 0.")
else:
    print("the number:", x ,"is positive.")

the number: 35 is positive.


***Question #5 (6 pts)***

- Create a list of numbers from 1 to 15 (15 included)
- Given this list, use for loop to detect and print only *odd* numbers.

In [257]:
# create the list from 1 to 15

x = list(range(1,16))
print(x)
# to detect odd numbers since when they're divided by 2 they have a remainder of 1
# and print only odd numbers
for num in x :
    if num % 2== 1 :
        print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
1
3
5
7
9
11
13
15


***Question #6 (4 pts)*** Zaim
- Use a while loop to print numbers from 1 to 10.

In [259]:
total = 0

while total < 10: 
 
    total = total + 1
    print(total)
# The loop runs while total is less than 10
# total increases each time starting from 0, so the loop eventually stops at 10

1
2
3
4
5
6
7
8
9
10


***Question #7 (6 pts)*** Jasper 
- Modify the above while loop so that it prints only the even numbers from 1 to 15.

In [261]:
total = 0

while total < 15: 
    total = total + 1
    if total % 2 != 0:
    
        continue
    print(total)
#This loop increases total by 1 each time while it is less than 15.
# If total is odd, continue skips that number, so only even numbers are printed.

2
4
6
8
10
12
14


### Part C: Functions (20 points)

***Question #8 (6 pts)*** Yashas
- Write a function square(x) that returns the square of x
- Test it for a single number
- Test it for a numpy array x, say x = np.array([1, 2, 3, 4]) 

In [263]:
#part 1
def sqr(x):
    """
    the sqr function takes the square of any number, array
    
    (it will be in the form of x^2)
    """
    Y = x ** 2
    return Y
# This code helps create a function that squares any number like x, or array.


In [327]:
#part 2
print(4)
sqr(4)
#helps ensure that the function created will correctly produce the square of any number

4


16

In [325]:
#part 3
import numpy as np # as we need to create an array, need to import the numpy library to create the array
x = np.array([1,2,3,4])
print(x)
print(sqr(x))
#helps show that the function created will correctly produce the square of each element in an array

[1 2 3 4]
[ 1  4  9 16]


***Question #9 (6 pts)*** Zaim
- Write a function mean(numbers) that returns the average.
- Create an object--a list of numbers.
- Call the function using the object and print the result.

In [267]:
def mean(numbers): # Creates function that sums the numbers in a list/tuple and divides them by number of numbers.
    
    """ 
    This sums the numbers in a list or tuple and then divides them 
    by the number of elements in the list aka taking the mean value.
    """
    answer= sum(numbers)/len(numbers)
    return answer
    
z= [1, 2, 9, 4] #creates object- a list of numbers
print(z)
print(f"Average of the list z above is {mean(z)}") # calls mean function on list z

[1, 2, 9, 4]
Average of the list z above is 4.0


***Question #10 (8 pts)*** Taha

Write a function that classifies a number:

- "low" if x < 0.3, "high" otherwise
- create an object or instance, a single number
- call the function and print the result

In [323]:
def classify_number(x):
    """
    This function takes a number x and classifies it as either
    'low' if it is less than 0.3, or 'high' otherwise.
    """
    
    # Classifies  x as low if it's less than 0.3 and high otherwise
    if x < 0.3:
        return "low"   # Return "low" if condition is true
    else:
        return "high"  # Return "high" if condition is false


# Create a number (object/instance)
num = 0.25
print(num)

# Call the function on number =0.25 and print the result
print(classify_number(num))

0.25
low


### Part 3: Numpy (20 points)

***Question #11 (4 pts)***
- Create a NumPy array from 0 to 9 
- Print its shape.

In [271]:
import numpy as np
# create the NumPy array
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x)
# print its shape
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


***Question #12 (6 pts)*** Jasper
- Generate an array of 10 random numbers between 0 and 1.
- Compute and Print its mean.

In [273]:
np.random.seed (100) #set random seed 

x = np.random.rand(10) #randomly generate 10 numbers betwen 0 and 1
print(x) #print to check numbers

x_bar = np.mean(x) #mean of the array of 10 numbers

print(x_bar)


[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333]
0.4425757785871915


***Question #13 (6 pts)*** Yashas
- Create a numpy array x
- Compute and print x*np.log(x)

In [312]:
#part 1
import numpy as np # as we are doing mathematical operations, and creating arrays, need to import the numpy library
np.random.seed(42) # helps ensure that the random numbers in the array stay fixed in subsequent lines of code
x = np.random.rand(10) # creates an array with 10 random numbers
print(x)
#assuming that there was no requirement to create a specific array

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


In [310]:
#part 2
y = x * np.log(x)
print(y) # two classes of the same shape multiplying each other.

[-0.3678195  -0.04805069 -0.2283697  -0.30715011 -0.28984828 -0.28982759
 -0.16529851 -0.12444092 -0.3059489  -0.2444328 ]


Part D: Comprehension
(10 points)

***Question #14 (4 pts)*** Taha
- Create a list containing the squares of only the even numbers of list = [1, 2, 3, 4, 5, 6, 7, 8].           

In [314]:
lst = list(range(1,9)) #Creates list of 1-8 not including 9
print(lst)
squares_even = [x**2 for x in lst if x % 2 == 0] # Create a list of squares of only the even numbers
# as they're identified by a remainder of zero when divided by 2
print(squares_even) 

[1, 2, 3, 4, 5, 6, 7, 8]
[4, 16, 36, 64]


***Question #15 (6 pts)*** Taha
- create a dictionary for the prices of banana, apple and organge (assign prices)
- create a new dictionary using comprehension with prices increased by 10%.

In [329]:
prices = {"banana": 1.00,
          "apple": 1.50,
          "orange": 1.20} # Create a dictionary with original prices for banana, apple and orange
print(prices)
new_prices = {item: price * 1.10 for item, price in prices.items()} 
# Create a new dictionary with prices increased by 10%
print(new_prices)

{'banana': 1.0, 'apple': 1.5, 'orange': 1.2}
{'banana': 1.1, 'apple': 1.6500000000000001, 'orange': 1.32}
